var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blogs/[BLOGID]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b9115bec._.js")
R.c("server/chunks/ssr/learn-nextjs_7a697f55._.js")
R.c("server/chunks/ssr/learn-nextjs_c2354e88._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3496f8d2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ac4b743d._.js")
R.c("server/chunks/ssr/34b04_next_dist_1cd8bf3e._.js")
R.c("server/chunks/ssr/learn-nextjs_app_db2824aa._.js")
R.c("server/chunks/ssr/34b04_next_dist_client_components_builtin_global-error_b2de5707.js")
R.c("server/chunks/ssr/learn-nextjs_app_layout_2a4f7ce9.js")
R.c("server/chunks/ssr/learn-nextjs_app_not-found_9069b2a5.js")
R.c("server/chunks/ssr/34b04_next_dist_client_components_20162461._.js")
R.c("server/chunks/ssr/34b04_next_dist_client_components_builtin_unauthorized_959396d0.js")
R.c("server/chunks/ssr/learn-nextjs__next-internal_server_app_blogs_[BLOGID]_page_actions_0776a76e.js")
R.m(78034)
module.exports=R.m(78034).exports
